#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://www.meguru.com.cn:3306/hubu_student_infomation?serverTimezone=UTC&useSSL=false
#    username: root
#    password: jiaoziang123

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hubu_student_infomation?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456

mybatis:
  mapperLocations: classpath*:/mybatis/*.xml