package cn.com.meguru.dao.mapper;

import cn.com.meguru.entity.SourceOfStudent;
import cn.com.meguru.entity.SourceOfStudentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SourceOfStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_of_student
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    long countByExample(SourceOfStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_of_student
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    int deleteByExample(SourceOfStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_of_student
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    int insert(SourceOfStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_of_student
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    int insertSelective(SourceOfStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_of_student
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    List<SourceOfStudent> selectByExample(SourceOfStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_of_student
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    int updateByExampleSelective(@Param("record") SourceOfStudent record, @Param("example") SourceOfStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_of_student
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    int updateByExample(@Param("record") SourceOfStudent record, @Param("example") SourceOfStudentExample example);
}