package cn.com.meguru.dao.mapper;

import cn.com.meguru.entity.StatusOfStudent;
import cn.com.meguru.entity.StatusOfStudentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StatusOfStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status_of_student
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    long countByExample(StatusOfStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status_of_student
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    int deleteByExample(StatusOfStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status_of_student
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    int insert(StatusOfStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status_of_student
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    int insertSelective(StatusOfStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status_of_student
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    List<StatusOfStudent> selectByExample(StatusOfStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status_of_student
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    int updateByExampleSelective(@Param("record") StatusOfStudent record, @Param("example") StatusOfStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status_of_student
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    int updateByExample(@Param("record") StatusOfStudent record, @Param("example") StatusOfStudentExample example);
}