package cn.com.meguru.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class SourceOfStudentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table source_of_student
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table source_of_student
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table source_of_student
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_of_student
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public SourceOfStudentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_of_student
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_of_student
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_of_student
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_of_student
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_of_student
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_of_student
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_of_student
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_of_student
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_of_student
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_of_student
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table source_of_student
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andEducationalSystemIsNull() {
            addCriterion("educational_system is null");
            return (Criteria) this;
        }

        public Criteria andEducationalSystemIsNotNull() {
            addCriterion("educational_system is not null");
            return (Criteria) this;
        }

        public Criteria andEducationalSystemEqualTo(Byte value) {
            addCriterion("educational_system =", value, "educationalSystem");
            return (Criteria) this;
        }

        public Criteria andEducationalSystemNotEqualTo(Byte value) {
            addCriterion("educational_system <>", value, "educationalSystem");
            return (Criteria) this;
        }

        public Criteria andEducationalSystemGreaterThan(Byte value) {
            addCriterion("educational_system >", value, "educationalSystem");
            return (Criteria) this;
        }

        public Criteria andEducationalSystemGreaterThanOrEqualTo(Byte value) {
            addCriterion("educational_system >=", value, "educationalSystem");
            return (Criteria) this;
        }

        public Criteria andEducationalSystemLessThan(Byte value) {
            addCriterion("educational_system <", value, "educationalSystem");
            return (Criteria) this;
        }

        public Criteria andEducationalSystemLessThanOrEqualTo(Byte value) {
            addCriterion("educational_system <=", value, "educationalSystem");
            return (Criteria) this;
        }

        public Criteria andEducationalSystemIn(List<Byte> values) {
            addCriterion("educational_system in", values, "educationalSystem");
            return (Criteria) this;
        }

        public Criteria andEducationalSystemNotIn(List<Byte> values) {
            addCriterion("educational_system not in", values, "educationalSystem");
            return (Criteria) this;
        }

        public Criteria andEducationalSystemBetween(Byte value1, Byte value2) {
            addCriterion("educational_system between", value1, value2, "educationalSystem");
            return (Criteria) this;
        }

        public Criteria andEducationalSystemNotBetween(Byte value1, Byte value2) {
            addCriterion("educational_system not between", value1, value2, "educationalSystem");
            return (Criteria) this;
        }

        public Criteria andDegreeIsNull() {
            addCriterion("degree is null");
            return (Criteria) this;
        }

        public Criteria andDegreeIsNotNull() {
            addCriterion("degree is not null");
            return (Criteria) this;
        }

        public Criteria andDegreeEqualTo(String value) {
            addCriterion("degree =", value, "degree");
            return (Criteria) this;
        }

        public Criteria andDegreeNotEqualTo(String value) {
            addCriterion("degree <>", value, "degree");
            return (Criteria) this;
        }

        public Criteria andDegreeGreaterThan(String value) {
            addCriterion("degree >", value, "degree");
            return (Criteria) this;
        }

        public Criteria andDegreeGreaterThanOrEqualTo(String value) {
            addCriterion("degree >=", value, "degree");
            return (Criteria) this;
        }

        public Criteria andDegreeLessThan(String value) {
            addCriterion("degree <", value, "degree");
            return (Criteria) this;
        }

        public Criteria andDegreeLessThanOrEqualTo(String value) {
            addCriterion("degree <=", value, "degree");
            return (Criteria) this;
        }

        public Criteria andDegreeLike(String value) {
            addCriterion("degree like", value, "degree");
            return (Criteria) this;
        }

        public Criteria andDegreeNotLike(String value) {
            addCriterion("degree not like", value, "degree");
            return (Criteria) this;
        }

        public Criteria andDegreeIn(List<String> values) {
            addCriterion("degree in", values, "degree");
            return (Criteria) this;
        }

        public Criteria andDegreeNotIn(List<String> values) {
            addCriterion("degree not in", values, "degree");
            return (Criteria) this;
        }

        public Criteria andDegreeBetween(String value1, String value2) {
            addCriterion("degree between", value1, value2, "degree");
            return (Criteria) this;
        }

        public Criteria andDegreeNotBetween(String value1, String value2) {
            addCriterion("degree not between", value1, value2, "degree");
            return (Criteria) this;
        }

        public Criteria andTrainingMethodIsNull() {
            addCriterion("training_method is null");
            return (Criteria) this;
        }

        public Criteria andTrainingMethodIsNotNull() {
            addCriterion("training_method is not null");
            return (Criteria) this;
        }

        public Criteria andTrainingMethodEqualTo(String value) {
            addCriterion("training_method =", value, "trainingMethod");
            return (Criteria) this;
        }

        public Criteria andTrainingMethodNotEqualTo(String value) {
            addCriterion("training_method <>", value, "trainingMethod");
            return (Criteria) this;
        }

        public Criteria andTrainingMethodGreaterThan(String value) {
            addCriterion("training_method >", value, "trainingMethod");
            return (Criteria) this;
        }

        public Criteria andTrainingMethodGreaterThanOrEqualTo(String value) {
            addCriterion("training_method >=", value, "trainingMethod");
            return (Criteria) this;
        }

        public Criteria andTrainingMethodLessThan(String value) {
            addCriterion("training_method <", value, "trainingMethod");
            return (Criteria) this;
        }

        public Criteria andTrainingMethodLessThanOrEqualTo(String value) {
            addCriterion("training_method <=", value, "trainingMethod");
            return (Criteria) this;
        }

        public Criteria andTrainingMethodLike(String value) {
            addCriterion("training_method like", value, "trainingMethod");
            return (Criteria) this;
        }

        public Criteria andTrainingMethodNotLike(String value) {
            addCriterion("training_method not like", value, "trainingMethod");
            return (Criteria) this;
        }

        public Criteria andTrainingMethodIn(List<String> values) {
            addCriterion("training_method in", values, "trainingMethod");
            return (Criteria) this;
        }

        public Criteria andTrainingMethodNotIn(List<String> values) {
            addCriterion("training_method not in", values, "trainingMethod");
            return (Criteria) this;
        }

        public Criteria andTrainingMethodBetween(String value1, String value2) {
            addCriterion("training_method between", value1, value2, "trainingMethod");
            return (Criteria) this;
        }

        public Criteria andTrainingMethodNotBetween(String value1, String value2) {
            addCriterion("training_method not between", value1, value2, "trainingMethod");
            return (Criteria) this;
        }

        public Criteria andGraduationYearIsNull() {
            addCriterion("graduation_year is null");
            return (Criteria) this;
        }

        public Criteria andGraduationYearIsNotNull() {
            addCriterion("graduation_year is not null");
            return (Criteria) this;
        }

        public Criteria andGraduationYearEqualTo(String value) {
            addCriterion("graduation_year =", value, "graduationYear");
            return (Criteria) this;
        }

        public Criteria andGraduationYearNotEqualTo(String value) {
            addCriterion("graduation_year <>", value, "graduationYear");
            return (Criteria) this;
        }

        public Criteria andGraduationYearGreaterThan(String value) {
            addCriterion("graduation_year >", value, "graduationYear");
            return (Criteria) this;
        }

        public Criteria andGraduationYearGreaterThanOrEqualTo(String value) {
            addCriterion("graduation_year >=", value, "graduationYear");
            return (Criteria) this;
        }

        public Criteria andGraduationYearLessThan(String value) {
            addCriterion("graduation_year <", value, "graduationYear");
            return (Criteria) this;
        }

        public Criteria andGraduationYearLessThanOrEqualTo(String value) {
            addCriterion("graduation_year <=", value, "graduationYear");
            return (Criteria) this;
        }

        public Criteria andGraduationYearLike(String value) {
            addCriterion("graduation_year like", value, "graduationYear");
            return (Criteria) this;
        }

        public Criteria andGraduationYearNotLike(String value) {
            addCriterion("graduation_year not like", value, "graduationYear");
            return (Criteria) this;
        }

        public Criteria andGraduationYearIn(List<String> values) {
            addCriterion("graduation_year in", values, "graduationYear");
            return (Criteria) this;
        }

        public Criteria andGraduationYearNotIn(List<String> values) {
            addCriterion("graduation_year not in", values, "graduationYear");
            return (Criteria) this;
        }

        public Criteria andGraduationYearBetween(String value1, String value2) {
            addCriterion("graduation_year between", value1, value2, "graduationYear");
            return (Criteria) this;
        }

        public Criteria andGraduationYearNotBetween(String value1, String value2) {
            addCriterion("graduation_year not between", value1, value2, "graduationYear");
            return (Criteria) this;
        }

        public Criteria andProfessionalDirectionIsNull() {
            addCriterion("professional_direction is null");
            return (Criteria) this;
        }

        public Criteria andProfessionalDirectionIsNotNull() {
            addCriterion("professional_direction is not null");
            return (Criteria) this;
        }

        public Criteria andProfessionalDirectionEqualTo(String value) {
            addCriterion("professional_direction =", value, "professionalDirection");
            return (Criteria) this;
        }

        public Criteria andProfessionalDirectionNotEqualTo(String value) {
            addCriterion("professional_direction <>", value, "professionalDirection");
            return (Criteria) this;
        }

        public Criteria andProfessionalDirectionGreaterThan(String value) {
            addCriterion("professional_direction >", value, "professionalDirection");
            return (Criteria) this;
        }

        public Criteria andProfessionalDirectionGreaterThanOrEqualTo(String value) {
            addCriterion("professional_direction >=", value, "professionalDirection");
            return (Criteria) this;
        }

        public Criteria andProfessionalDirectionLessThan(String value) {
            addCriterion("professional_direction <", value, "professionalDirection");
            return (Criteria) this;
        }

        public Criteria andProfessionalDirectionLessThanOrEqualTo(String value) {
            addCriterion("professional_direction <=", value, "professionalDirection");
            return (Criteria) this;
        }

        public Criteria andProfessionalDirectionLike(String value) {
            addCriterion("professional_direction like", value, "professionalDirection");
            return (Criteria) this;
        }

        public Criteria andProfessionalDirectionNotLike(String value) {
            addCriterion("professional_direction not like", value, "professionalDirection");
            return (Criteria) this;
        }

        public Criteria andProfessionalDirectionIn(List<String> values) {
            addCriterion("professional_direction in", values, "professionalDirection");
            return (Criteria) this;
        }

        public Criteria andProfessionalDirectionNotIn(List<String> values) {
            addCriterion("professional_direction not in", values, "professionalDirection");
            return (Criteria) this;
        }

        public Criteria andProfessionalDirectionBetween(String value1, String value2) {
            addCriterion("professional_direction between", value1, value2, "professionalDirection");
            return (Criteria) this;
        }

        public Criteria andProfessionalDirectionNotBetween(String value1, String value2) {
            addCriterion("professional_direction not between", value1, value2, "professionalDirection");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusIsNull() {
            addCriterion("marital_status is null");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusIsNotNull() {
            addCriterion("marital_status is not null");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusEqualTo(String value) {
            addCriterion("marital_status =", value, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusNotEqualTo(String value) {
            addCriterion("marital_status <>", value, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusGreaterThan(String value) {
            addCriterion("marital_status >", value, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusGreaterThanOrEqualTo(String value) {
            addCriterion("marital_status >=", value, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusLessThan(String value) {
            addCriterion("marital_status <", value, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusLessThanOrEqualTo(String value) {
            addCriterion("marital_status <=", value, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusLike(String value) {
            addCriterion("marital_status like", value, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusNotLike(String value) {
            addCriterion("marital_status not like", value, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusIn(List<String> values) {
            addCriterion("marital_status in", values, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusNotIn(List<String> values) {
            addCriterion("marital_status not in", values, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusBetween(String value1, String value2) {
            addCriterion("marital_status between", value1, value2, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusNotBetween(String value1, String value2) {
            addCriterion("marital_status not between", value1, value2, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andPoliticalStatusIsNull() {
            addCriterion("political_status is null");
            return (Criteria) this;
        }

        public Criteria andPoliticalStatusIsNotNull() {
            addCriterion("political_status is not null");
            return (Criteria) this;
        }

        public Criteria andPoliticalStatusEqualTo(String value) {
            addCriterion("political_status =", value, "politicalStatus");
            return (Criteria) this;
        }

        public Criteria andPoliticalStatusNotEqualTo(String value) {
            addCriterion("political_status <>", value, "politicalStatus");
            return (Criteria) this;
        }

        public Criteria andPoliticalStatusGreaterThan(String value) {
            addCriterion("political_status >", value, "politicalStatus");
            return (Criteria) this;
        }

        public Criteria andPoliticalStatusGreaterThanOrEqualTo(String value) {
            addCriterion("political_status >=", value, "politicalStatus");
            return (Criteria) this;
        }

        public Criteria andPoliticalStatusLessThan(String value) {
            addCriterion("political_status <", value, "politicalStatus");
            return (Criteria) this;
        }

        public Criteria andPoliticalStatusLessThanOrEqualTo(String value) {
            addCriterion("political_status <=", value, "politicalStatus");
            return (Criteria) this;
        }

        public Criteria andPoliticalStatusLike(String value) {
            addCriterion("political_status like", value, "politicalStatus");
            return (Criteria) this;
        }

        public Criteria andPoliticalStatusNotLike(String value) {
            addCriterion("political_status not like", value, "politicalStatus");
            return (Criteria) this;
        }

        public Criteria andPoliticalStatusIn(List<String> values) {
            addCriterion("political_status in", values, "politicalStatus");
            return (Criteria) this;
        }

        public Criteria andPoliticalStatusNotIn(List<String> values) {
            addCriterion("political_status not in", values, "politicalStatus");
            return (Criteria) this;
        }

        public Criteria andPoliticalStatusBetween(String value1, String value2) {
            addCriterion("political_status between", value1, value2, "politicalStatus");
            return (Criteria) this;
        }

        public Criteria andPoliticalStatusNotBetween(String value1, String value2) {
            addCriterion("political_status not between", value1, value2, "politicalStatus");
            return (Criteria) this;
        }

        public Criteria andNationalityIsNull() {
            addCriterion("nationality is null");
            return (Criteria) this;
        }

        public Criteria andNationalityIsNotNull() {
            addCriterion("nationality is not null");
            return (Criteria) this;
        }

        public Criteria andNationalityEqualTo(String value) {
            addCriterion("nationality =", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityNotEqualTo(String value) {
            addCriterion("nationality <>", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityGreaterThan(String value) {
            addCriterion("nationality >", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityGreaterThanOrEqualTo(String value) {
            addCriterion("nationality >=", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityLessThan(String value) {
            addCriterion("nationality <", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityLessThanOrEqualTo(String value) {
            addCriterion("nationality <=", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityLike(String value) {
            addCriterion("nationality like", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityNotLike(String value) {
            addCriterion("nationality not like", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityIn(List<String> values) {
            addCriterion("nationality in", values, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityNotIn(List<String> values) {
            addCriterion("nationality not in", values, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityBetween(String value1, String value2) {
            addCriterion("nationality between", value1, value2, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityNotBetween(String value1, String value2) {
            addCriterion("nationality not between", value1, value2, "nationality");
            return (Criteria) this;
        }

        public Criteria andDateOfBirthIsNull() {
            addCriterion("date_of_birth is null");
            return (Criteria) this;
        }

        public Criteria andDateOfBirthIsNotNull() {
            addCriterion("date_of_birth is not null");
            return (Criteria) this;
        }

        public Criteria andDateOfBirthEqualTo(Date value) {
            addCriterionForJDBCDate("date_of_birth =", value, "dateOfBirth");
            return (Criteria) this;
        }

        public Criteria andDateOfBirthNotEqualTo(Date value) {
            addCriterionForJDBCDate("date_of_birth <>", value, "dateOfBirth");
            return (Criteria) this;
        }

        public Criteria andDateOfBirthGreaterThan(Date value) {
            addCriterionForJDBCDate("date_of_birth >", value, "dateOfBirth");
            return (Criteria) this;
        }

        public Criteria andDateOfBirthGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("date_of_birth >=", value, "dateOfBirth");
            return (Criteria) this;
        }

        public Criteria andDateOfBirthLessThan(Date value) {
            addCriterionForJDBCDate("date_of_birth <", value, "dateOfBirth");
            return (Criteria) this;
        }

        public Criteria andDateOfBirthLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("date_of_birth <=", value, "dateOfBirth");
            return (Criteria) this;
        }

        public Criteria andDateOfBirthIn(List<Date> values) {
            addCriterionForJDBCDate("date_of_birth in", values, "dateOfBirth");
            return (Criteria) this;
        }

        public Criteria andDateOfBirthNotIn(List<Date> values) {
            addCriterionForJDBCDate("date_of_birth not in", values, "dateOfBirth");
            return (Criteria) this;
        }

        public Criteria andDateOfBirthBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("date_of_birth between", value1, value2, "dateOfBirth");
            return (Criteria) this;
        }

        public Criteria andDateOfBirthNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("date_of_birth not between", value1, value2, "dateOfBirth");
            return (Criteria) this;
        }

        public Criteria andDateOfStartSchoolIsNull() {
            addCriterion("date_of_start_school is null");
            return (Criteria) this;
        }

        public Criteria andDateOfStartSchoolIsNotNull() {
            addCriterion("date_of_start_school is not null");
            return (Criteria) this;
        }

        public Criteria andDateOfStartSchoolEqualTo(Date value) {
            addCriterionForJDBCDate("date_of_start_school =", value, "dateOfStartSchool");
            return (Criteria) this;
        }

        public Criteria andDateOfStartSchoolNotEqualTo(Date value) {
            addCriterionForJDBCDate("date_of_start_school <>", value, "dateOfStartSchool");
            return (Criteria) this;
        }

        public Criteria andDateOfStartSchoolGreaterThan(Date value) {
            addCriterionForJDBCDate("date_of_start_school >", value, "dateOfStartSchool");
            return (Criteria) this;
        }

        public Criteria andDateOfStartSchoolGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("date_of_start_school >=", value, "dateOfStartSchool");
            return (Criteria) this;
        }

        public Criteria andDateOfStartSchoolLessThan(Date value) {
            addCriterionForJDBCDate("date_of_start_school <", value, "dateOfStartSchool");
            return (Criteria) this;
        }

        public Criteria andDateOfStartSchoolLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("date_of_start_school <=", value, "dateOfStartSchool");
            return (Criteria) this;
        }

        public Criteria andDateOfStartSchoolIn(List<Date> values) {
            addCriterionForJDBCDate("date_of_start_school in", values, "dateOfStartSchool");
            return (Criteria) this;
        }

        public Criteria andDateOfStartSchoolNotIn(List<Date> values) {
            addCriterionForJDBCDate("date_of_start_school not in", values, "dateOfStartSchool");
            return (Criteria) this;
        }

        public Criteria andDateOfStartSchoolBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("date_of_start_school between", value1, value2, "dateOfStartSchool");
            return (Criteria) this;
        }

        public Criteria andDateOfStartSchoolNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("date_of_start_school not between", value1, value2, "dateOfStartSchool");
            return (Criteria) this;
        }

        public Criteria andMajoringInForeignLanguageIsNull() {
            addCriterion("majoring_in_foreign_language is null");
            return (Criteria) this;
        }

        public Criteria andMajoringInForeignLanguageIsNotNull() {
            addCriterion("majoring_in_foreign_language is not null");
            return (Criteria) this;
        }

        public Criteria andMajoringInForeignLanguageEqualTo(String value) {
            addCriterion("majoring_in_foreign_language =", value, "majoringInForeignLanguage");
            return (Criteria) this;
        }

        public Criteria andMajoringInForeignLanguageNotEqualTo(String value) {
            addCriterion("majoring_in_foreign_language <>", value, "majoringInForeignLanguage");
            return (Criteria) this;
        }

        public Criteria andMajoringInForeignLanguageGreaterThan(String value) {
            addCriterion("majoring_in_foreign_language >", value, "majoringInForeignLanguage");
            return (Criteria) this;
        }

        public Criteria andMajoringInForeignLanguageGreaterThanOrEqualTo(String value) {
            addCriterion("majoring_in_foreign_language >=", value, "majoringInForeignLanguage");
            return (Criteria) this;
        }

        public Criteria andMajoringInForeignLanguageLessThan(String value) {
            addCriterion("majoring_in_foreign_language <", value, "majoringInForeignLanguage");
            return (Criteria) this;
        }

        public Criteria andMajoringInForeignLanguageLessThanOrEqualTo(String value) {
            addCriterion("majoring_in_foreign_language <=", value, "majoringInForeignLanguage");
            return (Criteria) this;
        }

        public Criteria andMajoringInForeignLanguageLike(String value) {
            addCriterion("majoring_in_foreign_language like", value, "majoringInForeignLanguage");
            return (Criteria) this;
        }

        public Criteria andMajoringInForeignLanguageNotLike(String value) {
            addCriterion("majoring_in_foreign_language not like", value, "majoringInForeignLanguage");
            return (Criteria) this;
        }

        public Criteria andMajoringInForeignLanguageIn(List<String> values) {
            addCriterion("majoring_in_foreign_language in", values, "majoringInForeignLanguage");
            return (Criteria) this;
        }

        public Criteria andMajoringInForeignLanguageNotIn(List<String> values) {
            addCriterion("majoring_in_foreign_language not in", values, "majoringInForeignLanguage");
            return (Criteria) this;
        }

        public Criteria andMajoringInForeignLanguageBetween(String value1, String value2) {
            addCriterion("majoring_in_foreign_language between", value1, value2, "majoringInForeignLanguage");
            return (Criteria) this;
        }

        public Criteria andMajoringInForeignLanguageNotBetween(String value1, String value2) {
            addCriterion("majoring_in_foreign_language not between", value1, value2, "majoringInForeignLanguage");
            return (Criteria) this;
        }

        public Criteria andCityOrVillageIsNull() {
            addCriterion("city_or_village is null");
            return (Criteria) this;
        }

        public Criteria andCityOrVillageIsNotNull() {
            addCriterion("city_or_village is not null");
            return (Criteria) this;
        }

        public Criteria andCityOrVillageEqualTo(String value) {
            addCriterion("city_or_village =", value, "cityOrVillage");
            return (Criteria) this;
        }

        public Criteria andCityOrVillageNotEqualTo(String value) {
            addCriterion("city_or_village <>", value, "cityOrVillage");
            return (Criteria) this;
        }

        public Criteria andCityOrVillageGreaterThan(String value) {
            addCriterion("city_or_village >", value, "cityOrVillage");
            return (Criteria) this;
        }

        public Criteria andCityOrVillageGreaterThanOrEqualTo(String value) {
            addCriterion("city_or_village >=", value, "cityOrVillage");
            return (Criteria) this;
        }

        public Criteria andCityOrVillageLessThan(String value) {
            addCriterion("city_or_village <", value, "cityOrVillage");
            return (Criteria) this;
        }

        public Criteria andCityOrVillageLessThanOrEqualTo(String value) {
            addCriterion("city_or_village <=", value, "cityOrVillage");
            return (Criteria) this;
        }

        public Criteria andCityOrVillageLike(String value) {
            addCriterion("city_or_village like", value, "cityOrVillage");
            return (Criteria) this;
        }

        public Criteria andCityOrVillageNotLike(String value) {
            addCriterion("city_or_village not like", value, "cityOrVillage");
            return (Criteria) this;
        }

        public Criteria andCityOrVillageIn(List<String> values) {
            addCriterion("city_or_village in", values, "cityOrVillage");
            return (Criteria) this;
        }

        public Criteria andCityOrVillageNotIn(List<String> values) {
            addCriterion("city_or_village not in", values, "cityOrVillage");
            return (Criteria) this;
        }

        public Criteria andCityOrVillageBetween(String value1, String value2) {
            addCriterion("city_or_village between", value1, value2, "cityOrVillage");
            return (Criteria) this;
        }

        public Criteria andCityOrVillageNotBetween(String value1, String value2) {
            addCriterion("city_or_village not between", value1, value2, "cityOrVillage");
            return (Criteria) this;
        }

        public Criteria andAccountToSchoolIsNull() {
            addCriterion("account_to_school is null");
            return (Criteria) this;
        }

        public Criteria andAccountToSchoolIsNotNull() {
            addCriterion("account_to_school is not null");
            return (Criteria) this;
        }

        public Criteria andAccountToSchoolEqualTo(String value) {
            addCriterion("account_to_school =", value, "accountToSchool");
            return (Criteria) this;
        }

        public Criteria andAccountToSchoolNotEqualTo(String value) {
            addCriterion("account_to_school <>", value, "accountToSchool");
            return (Criteria) this;
        }

        public Criteria andAccountToSchoolGreaterThan(String value) {
            addCriterion("account_to_school >", value, "accountToSchool");
            return (Criteria) this;
        }

        public Criteria andAccountToSchoolGreaterThanOrEqualTo(String value) {
            addCriterion("account_to_school >=", value, "accountToSchool");
            return (Criteria) this;
        }

        public Criteria andAccountToSchoolLessThan(String value) {
            addCriterion("account_to_school <", value, "accountToSchool");
            return (Criteria) this;
        }

        public Criteria andAccountToSchoolLessThanOrEqualTo(String value) {
            addCriterion("account_to_school <=", value, "accountToSchool");
            return (Criteria) this;
        }

        public Criteria andAccountToSchoolLike(String value) {
            addCriterion("account_to_school like", value, "accountToSchool");
            return (Criteria) this;
        }

        public Criteria andAccountToSchoolNotLike(String value) {
            addCriterion("account_to_school not like", value, "accountToSchool");
            return (Criteria) this;
        }

        public Criteria andAccountToSchoolIn(List<String> values) {
            addCriterion("account_to_school in", values, "accountToSchool");
            return (Criteria) this;
        }

        public Criteria andAccountToSchoolNotIn(List<String> values) {
            addCriterion("account_to_school not in", values, "accountToSchool");
            return (Criteria) this;
        }

        public Criteria andAccountToSchoolBetween(String value1, String value2) {
            addCriterion("account_to_school between", value1, value2, "accountToSchool");
            return (Criteria) this;
        }

        public Criteria andAccountToSchoolNotBetween(String value1, String value2) {
            addCriterion("account_to_school not between", value1, value2, "accountToSchool");
            return (Criteria) this;
        }

        public Criteria andArchivesToSchoolIsNull() {
            addCriterion("archives_to_school is null");
            return (Criteria) this;
        }

        public Criteria andArchivesToSchoolIsNotNull() {
            addCriterion("archives_to_school is not null");
            return (Criteria) this;
        }

        public Criteria andArchivesToSchoolEqualTo(String value) {
            addCriterion("archives_to_school =", value, "archivesToSchool");
            return (Criteria) this;
        }

        public Criteria andArchivesToSchoolNotEqualTo(String value) {
            addCriterion("archives_to_school <>", value, "archivesToSchool");
            return (Criteria) this;
        }

        public Criteria andArchivesToSchoolGreaterThan(String value) {
            addCriterion("archives_to_school >", value, "archivesToSchool");
            return (Criteria) this;
        }

        public Criteria andArchivesToSchoolGreaterThanOrEqualTo(String value) {
            addCriterion("archives_to_school >=", value, "archivesToSchool");
            return (Criteria) this;
        }

        public Criteria andArchivesToSchoolLessThan(String value) {
            addCriterion("archives_to_school <", value, "archivesToSchool");
            return (Criteria) this;
        }

        public Criteria andArchivesToSchoolLessThanOrEqualTo(String value) {
            addCriterion("archives_to_school <=", value, "archivesToSchool");
            return (Criteria) this;
        }

        public Criteria andArchivesToSchoolLike(String value) {
            addCriterion("archives_to_school like", value, "archivesToSchool");
            return (Criteria) this;
        }

        public Criteria andArchivesToSchoolNotLike(String value) {
            addCriterion("archives_to_school not like", value, "archivesToSchool");
            return (Criteria) this;
        }

        public Criteria andArchivesToSchoolIn(List<String> values) {
            addCriterion("archives_to_school in", values, "archivesToSchool");
            return (Criteria) this;
        }

        public Criteria andArchivesToSchoolNotIn(List<String> values) {
            addCriterion("archives_to_school not in", values, "archivesToSchool");
            return (Criteria) this;
        }

        public Criteria andArchivesToSchoolBetween(String value1, String value2) {
            addCriterion("archives_to_school between", value1, value2, "archivesToSchool");
            return (Criteria) this;
        }

        public Criteria andArchivesToSchoolNotBetween(String value1, String value2) {
            addCriterion("archives_to_school not between", value1, value2, "archivesToSchool");
            return (Criteria) this;
        }

        public Criteria andMajoringInForeignLanguageLevelIsNull() {
            addCriterion("majoring_in_foreign_language_level is null");
            return (Criteria) this;
        }

        public Criteria andMajoringInForeignLanguageLevelIsNotNull() {
            addCriterion("majoring_in_foreign_language_level is not null");
            return (Criteria) this;
        }

        public Criteria andMajoringInForeignLanguageLevelEqualTo(String value) {
            addCriterion("majoring_in_foreign_language_level =", value, "majoringInForeignLanguageLevel");
            return (Criteria) this;
        }

        public Criteria andMajoringInForeignLanguageLevelNotEqualTo(String value) {
            addCriterion("majoring_in_foreign_language_level <>", value, "majoringInForeignLanguageLevel");
            return (Criteria) this;
        }

        public Criteria andMajoringInForeignLanguageLevelGreaterThan(String value) {
            addCriterion("majoring_in_foreign_language_level >", value, "majoringInForeignLanguageLevel");
            return (Criteria) this;
        }

        public Criteria andMajoringInForeignLanguageLevelGreaterThanOrEqualTo(String value) {
            addCriterion("majoring_in_foreign_language_level >=", value, "majoringInForeignLanguageLevel");
            return (Criteria) this;
        }

        public Criteria andMajoringInForeignLanguageLevelLessThan(String value) {
            addCriterion("majoring_in_foreign_language_level <", value, "majoringInForeignLanguageLevel");
            return (Criteria) this;
        }

        public Criteria andMajoringInForeignLanguageLevelLessThanOrEqualTo(String value) {
            addCriterion("majoring_in_foreign_language_level <=", value, "majoringInForeignLanguageLevel");
            return (Criteria) this;
        }

        public Criteria andMajoringInForeignLanguageLevelLike(String value) {
            addCriterion("majoring_in_foreign_language_level like", value, "majoringInForeignLanguageLevel");
            return (Criteria) this;
        }

        public Criteria andMajoringInForeignLanguageLevelNotLike(String value) {
            addCriterion("majoring_in_foreign_language_level not like", value, "majoringInForeignLanguageLevel");
            return (Criteria) this;
        }

        public Criteria andMajoringInForeignLanguageLevelIn(List<String> values) {
            addCriterion("majoring_in_foreign_language_level in", values, "majoringInForeignLanguageLevel");
            return (Criteria) this;
        }

        public Criteria andMajoringInForeignLanguageLevelNotIn(List<String> values) {
            addCriterion("majoring_in_foreign_language_level not in", values, "majoringInForeignLanguageLevel");
            return (Criteria) this;
        }

        public Criteria andMajoringInForeignLanguageLevelBetween(String value1, String value2) {
            addCriterion("majoring_in_foreign_language_level between", value1, value2, "majoringInForeignLanguageLevel");
            return (Criteria) this;
        }

        public Criteria andMajoringInForeignLanguageLevelNotBetween(String value1, String value2) {
            addCriterion("majoring_in_foreign_language_level not between", value1, value2, "majoringInForeignLanguageLevel");
            return (Criteria) this;
        }

        public Criteria andHomeAddressIsNull() {
            addCriterion("home_address is null");
            return (Criteria) this;
        }

        public Criteria andHomeAddressIsNotNull() {
            addCriterion("home_address is not null");
            return (Criteria) this;
        }

        public Criteria andHomeAddressEqualTo(String value) {
            addCriterion("home_address =", value, "homeAddress");
            return (Criteria) this;
        }

        public Criteria andHomeAddressNotEqualTo(String value) {
            addCriterion("home_address <>", value, "homeAddress");
            return (Criteria) this;
        }

        public Criteria andHomeAddressGreaterThan(String value) {
            addCriterion("home_address >", value, "homeAddress");
            return (Criteria) this;
        }

        public Criteria andHomeAddressGreaterThanOrEqualTo(String value) {
            addCriterion("home_address >=", value, "homeAddress");
            return (Criteria) this;
        }

        public Criteria andHomeAddressLessThan(String value) {
            addCriterion("home_address <", value, "homeAddress");
            return (Criteria) this;
        }

        public Criteria andHomeAddressLessThanOrEqualTo(String value) {
            addCriterion("home_address <=", value, "homeAddress");
            return (Criteria) this;
        }

        public Criteria andHomeAddressLike(String value) {
            addCriterion("home_address like", value, "homeAddress");
            return (Criteria) this;
        }

        public Criteria andHomeAddressNotLike(String value) {
            addCriterion("home_address not like", value, "homeAddress");
            return (Criteria) this;
        }

        public Criteria andHomeAddressIn(List<String> values) {
            addCriterion("home_address in", values, "homeAddress");
            return (Criteria) this;
        }

        public Criteria andHomeAddressNotIn(List<String> values) {
            addCriterion("home_address not in", values, "homeAddress");
            return (Criteria) this;
        }

        public Criteria andHomeAddressBetween(String value1, String value2) {
            addCriterion("home_address between", value1, value2, "homeAddress");
            return (Criteria) this;
        }

        public Criteria andHomeAddressNotBetween(String value1, String value2) {
            addCriterion("home_address not between", value1, value2, "homeAddress");
            return (Criteria) this;
        }

        public Criteria andStudentAreaIsNull() {
            addCriterion("student_area is null");
            return (Criteria) this;
        }

        public Criteria andStudentAreaIsNotNull() {
            addCriterion("student_area is not null");
            return (Criteria) this;
        }

        public Criteria andStudentAreaEqualTo(String value) {
            addCriterion("student_area =", value, "studentArea");
            return (Criteria) this;
        }

        public Criteria andStudentAreaNotEqualTo(String value) {
            addCriterion("student_area <>", value, "studentArea");
            return (Criteria) this;
        }

        public Criteria andStudentAreaGreaterThan(String value) {
            addCriterion("student_area >", value, "studentArea");
            return (Criteria) this;
        }

        public Criteria andStudentAreaGreaterThanOrEqualTo(String value) {
            addCriterion("student_area >=", value, "studentArea");
            return (Criteria) this;
        }

        public Criteria andStudentAreaLessThan(String value) {
            addCriterion("student_area <", value, "studentArea");
            return (Criteria) this;
        }

        public Criteria andStudentAreaLessThanOrEqualTo(String value) {
            addCriterion("student_area <=", value, "studentArea");
            return (Criteria) this;
        }

        public Criteria andStudentAreaLike(String value) {
            addCriterion("student_area like", value, "studentArea");
            return (Criteria) this;
        }

        public Criteria andStudentAreaNotLike(String value) {
            addCriterion("student_area not like", value, "studentArea");
            return (Criteria) this;
        }

        public Criteria andStudentAreaIn(List<String> values) {
            addCriterion("student_area in", values, "studentArea");
            return (Criteria) this;
        }

        public Criteria andStudentAreaNotIn(List<String> values) {
            addCriterion("student_area not in", values, "studentArea");
            return (Criteria) this;
        }

        public Criteria andStudentAreaBetween(String value1, String value2) {
            addCriterion("student_area between", value1, value2, "studentArea");
            return (Criteria) this;
        }

        public Criteria andStudentAreaNotBetween(String value1, String value2) {
            addCriterion("student_area not between", value1, value2, "studentArea");
            return (Criteria) this;
        }

        public Criteria andOther1IsNull() {
            addCriterion("other1 is null");
            return (Criteria) this;
        }

        public Criteria andOther1IsNotNull() {
            addCriterion("other1 is not null");
            return (Criteria) this;
        }

        public Criteria andOther1EqualTo(String value) {
            addCriterion("other1 =", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotEqualTo(String value) {
            addCriterion("other1 <>", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1GreaterThan(String value) {
            addCriterion("other1 >", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1GreaterThanOrEqualTo(String value) {
            addCriterion("other1 >=", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1LessThan(String value) {
            addCriterion("other1 <", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1LessThanOrEqualTo(String value) {
            addCriterion("other1 <=", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1Like(String value) {
            addCriterion("other1 like", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotLike(String value) {
            addCriterion("other1 not like", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1In(List<String> values) {
            addCriterion("other1 in", values, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotIn(List<String> values) {
            addCriterion("other1 not in", values, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1Between(String value1, String value2) {
            addCriterion("other1 between", value1, value2, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotBetween(String value1, String value2) {
            addCriterion("other1 not between", value1, value2, "other1");
            return (Criteria) this;
        }

        public Criteria andOther2IsNull() {
            addCriterion("other2 is null");
            return (Criteria) this;
        }

        public Criteria andOther2IsNotNull() {
            addCriterion("other2 is not null");
            return (Criteria) this;
        }

        public Criteria andOther2EqualTo(String value) {
            addCriterion("other2 =", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotEqualTo(String value) {
            addCriterion("other2 <>", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2GreaterThan(String value) {
            addCriterion("other2 >", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2GreaterThanOrEqualTo(String value) {
            addCriterion("other2 >=", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2LessThan(String value) {
            addCriterion("other2 <", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2LessThanOrEqualTo(String value) {
            addCriterion("other2 <=", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2Like(String value) {
            addCriterion("other2 like", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotLike(String value) {
            addCriterion("other2 not like", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2In(List<String> values) {
            addCriterion("other2 in", values, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotIn(List<String> values) {
            addCriterion("other2 not in", values, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2Between(String value1, String value2) {
            addCriterion("other2 between", value1, value2, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotBetween(String value1, String value2) {
            addCriterion("other2 not between", value1, value2, "other2");
            return (Criteria) this;
        }

        public Criteria andHomeZipCodeIsNull() {
            addCriterion("home_zip_code is null");
            return (Criteria) this;
        }

        public Criteria andHomeZipCodeIsNotNull() {
            addCriterion("home_zip_code is not null");
            return (Criteria) this;
        }

        public Criteria andHomeZipCodeEqualTo(String value) {
            addCriterion("home_zip_code =", value, "homeZipCode");
            return (Criteria) this;
        }

        public Criteria andHomeZipCodeNotEqualTo(String value) {
            addCriterion("home_zip_code <>", value, "homeZipCode");
            return (Criteria) this;
        }

        public Criteria andHomeZipCodeGreaterThan(String value) {
            addCriterion("home_zip_code >", value, "homeZipCode");
            return (Criteria) this;
        }

        public Criteria andHomeZipCodeGreaterThanOrEqualTo(String value) {
            addCriterion("home_zip_code >=", value, "homeZipCode");
            return (Criteria) this;
        }

        public Criteria andHomeZipCodeLessThan(String value) {
            addCriterion("home_zip_code <", value, "homeZipCode");
            return (Criteria) this;
        }

        public Criteria andHomeZipCodeLessThanOrEqualTo(String value) {
            addCriterion("home_zip_code <=", value, "homeZipCode");
            return (Criteria) this;
        }

        public Criteria andHomeZipCodeLike(String value) {
            addCriterion("home_zip_code like", value, "homeZipCode");
            return (Criteria) this;
        }

        public Criteria andHomeZipCodeNotLike(String value) {
            addCriterion("home_zip_code not like", value, "homeZipCode");
            return (Criteria) this;
        }

        public Criteria andHomeZipCodeIn(List<String> values) {
            addCriterion("home_zip_code in", values, "homeZipCode");
            return (Criteria) this;
        }

        public Criteria andHomeZipCodeNotIn(List<String> values) {
            addCriterion("home_zip_code not in", values, "homeZipCode");
            return (Criteria) this;
        }

        public Criteria andHomeZipCodeBetween(String value1, String value2) {
            addCriterion("home_zip_code between", value1, value2, "homeZipCode");
            return (Criteria) this;
        }

        public Criteria andHomeZipCodeNotBetween(String value1, String value2) {
            addCriterion("home_zip_code not between", value1, value2, "homeZipCode");
            return (Criteria) this;
        }

        public Criteria andIsTeacherTrainingIsNull() {
            addCriterion("is_teacher_training is null");
            return (Criteria) this;
        }

        public Criteria andIsTeacherTrainingIsNotNull() {
            addCriterion("is_teacher_training is not null");
            return (Criteria) this;
        }

        public Criteria andIsTeacherTrainingEqualTo(String value) {
            addCriterion("is_teacher_training =", value, "isTeacherTraining");
            return (Criteria) this;
        }

        public Criteria andIsTeacherTrainingNotEqualTo(String value) {
            addCriterion("is_teacher_training <>", value, "isTeacherTraining");
            return (Criteria) this;
        }

        public Criteria andIsTeacherTrainingGreaterThan(String value) {
            addCriterion("is_teacher_training >", value, "isTeacherTraining");
            return (Criteria) this;
        }

        public Criteria andIsTeacherTrainingGreaterThanOrEqualTo(String value) {
            addCriterion("is_teacher_training >=", value, "isTeacherTraining");
            return (Criteria) this;
        }

        public Criteria andIsTeacherTrainingLessThan(String value) {
            addCriterion("is_teacher_training <", value, "isTeacherTraining");
            return (Criteria) this;
        }

        public Criteria andIsTeacherTrainingLessThanOrEqualTo(String value) {
            addCriterion("is_teacher_training <=", value, "isTeacherTraining");
            return (Criteria) this;
        }

        public Criteria andIsTeacherTrainingLike(String value) {
            addCriterion("is_teacher_training like", value, "isTeacherTraining");
            return (Criteria) this;
        }

        public Criteria andIsTeacherTrainingNotLike(String value) {
            addCriterion("is_teacher_training not like", value, "isTeacherTraining");
            return (Criteria) this;
        }

        public Criteria andIsTeacherTrainingIn(List<String> values) {
            addCriterion("is_teacher_training in", values, "isTeacherTraining");
            return (Criteria) this;
        }

        public Criteria andIsTeacherTrainingNotIn(List<String> values) {
            addCriterion("is_teacher_training not in", values, "isTeacherTraining");
            return (Criteria) this;
        }

        public Criteria andIsTeacherTrainingBetween(String value1, String value2) {
            addCriterion("is_teacher_training between", value1, value2, "isTeacherTraining");
            return (Criteria) this;
        }

        public Criteria andIsTeacherTrainingNotBetween(String value1, String value2) {
            addCriterion("is_teacher_training not between", value1, value2, "isTeacherTraining");
            return (Criteria) this;
        }

        public Criteria andQqIsNull() {
            addCriterion("qq is null");
            return (Criteria) this;
        }

        public Criteria andQqIsNotNull() {
            addCriterion("qq is not null");
            return (Criteria) this;
        }

        public Criteria andQqEqualTo(String value) {
            addCriterion("qq =", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotEqualTo(String value) {
            addCriterion("qq <>", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqGreaterThan(String value) {
            addCriterion("qq >", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqGreaterThanOrEqualTo(String value) {
            addCriterion("qq >=", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqLessThan(String value) {
            addCriterion("qq <", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqLessThanOrEqualTo(String value) {
            addCriterion("qq <=", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqLike(String value) {
            addCriterion("qq like", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotLike(String value) {
            addCriterion("qq not like", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqIn(List<String> values) {
            addCriterion("qq in", values, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotIn(List<String> values) {
            addCriterion("qq not in", values, "qq");
            return (Criteria) this;
        }

        public Criteria andQqBetween(String value1, String value2) {
            addCriterion("qq between", value1, value2, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotBetween(String value1, String value2) {
            addCriterion("qq not between", value1, value2, "qq");
            return (Criteria) this;
        }

        public Criteria andFamilyContactIsNull() {
            addCriterion("family_contact is null");
            return (Criteria) this;
        }

        public Criteria andFamilyContactIsNotNull() {
            addCriterion("family_contact is not null");
            return (Criteria) this;
        }

        public Criteria andFamilyContactEqualTo(String value) {
            addCriterion("family_contact =", value, "familyContact");
            return (Criteria) this;
        }

        public Criteria andFamilyContactNotEqualTo(String value) {
            addCriterion("family_contact <>", value, "familyContact");
            return (Criteria) this;
        }

        public Criteria andFamilyContactGreaterThan(String value) {
            addCriterion("family_contact >", value, "familyContact");
            return (Criteria) this;
        }

        public Criteria andFamilyContactGreaterThanOrEqualTo(String value) {
            addCriterion("family_contact >=", value, "familyContact");
            return (Criteria) this;
        }

        public Criteria andFamilyContactLessThan(String value) {
            addCriterion("family_contact <", value, "familyContact");
            return (Criteria) this;
        }

        public Criteria andFamilyContactLessThanOrEqualTo(String value) {
            addCriterion("family_contact <=", value, "familyContact");
            return (Criteria) this;
        }

        public Criteria andFamilyContactLike(String value) {
            addCriterion("family_contact like", value, "familyContact");
            return (Criteria) this;
        }

        public Criteria andFamilyContactNotLike(String value) {
            addCriterion("family_contact not like", value, "familyContact");
            return (Criteria) this;
        }

        public Criteria andFamilyContactIn(List<String> values) {
            addCriterion("family_contact in", values, "familyContact");
            return (Criteria) this;
        }

        public Criteria andFamilyContactNotIn(List<String> values) {
            addCriterion("family_contact not in", values, "familyContact");
            return (Criteria) this;
        }

        public Criteria andFamilyContactBetween(String value1, String value2) {
            addCriterion("family_contact between", value1, value2, "familyContact");
            return (Criteria) this;
        }

        public Criteria andFamilyContactNotBetween(String value1, String value2) {
            addCriterion("family_contact not between", value1, value2, "familyContact");
            return (Criteria) this;
        }

        public Criteria andFamilyPhoneIsNull() {
            addCriterion("family_phone is null");
            return (Criteria) this;
        }

        public Criteria andFamilyPhoneIsNotNull() {
            addCriterion("family_phone is not null");
            return (Criteria) this;
        }

        public Criteria andFamilyPhoneEqualTo(String value) {
            addCriterion("family_phone =", value, "familyPhone");
            return (Criteria) this;
        }

        public Criteria andFamilyPhoneNotEqualTo(String value) {
            addCriterion("family_phone <>", value, "familyPhone");
            return (Criteria) this;
        }

        public Criteria andFamilyPhoneGreaterThan(String value) {
            addCriterion("family_phone >", value, "familyPhone");
            return (Criteria) this;
        }

        public Criteria andFamilyPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("family_phone >=", value, "familyPhone");
            return (Criteria) this;
        }

        public Criteria andFamilyPhoneLessThan(String value) {
            addCriterion("family_phone <", value, "familyPhone");
            return (Criteria) this;
        }

        public Criteria andFamilyPhoneLessThanOrEqualTo(String value) {
            addCriterion("family_phone <=", value, "familyPhone");
            return (Criteria) this;
        }

        public Criteria andFamilyPhoneLike(String value) {
            addCriterion("family_phone like", value, "familyPhone");
            return (Criteria) this;
        }

        public Criteria andFamilyPhoneNotLike(String value) {
            addCriterion("family_phone not like", value, "familyPhone");
            return (Criteria) this;
        }

        public Criteria andFamilyPhoneIn(List<String> values) {
            addCriterion("family_phone in", values, "familyPhone");
            return (Criteria) this;
        }

        public Criteria andFamilyPhoneNotIn(List<String> values) {
            addCriterion("family_phone not in", values, "familyPhone");
            return (Criteria) this;
        }

        public Criteria andFamilyPhoneBetween(String value1, String value2) {
            addCriterion("family_phone between", value1, value2, "familyPhone");
            return (Criteria) this;
        }

        public Criteria andFamilyPhoneNotBetween(String value1, String value2) {
            addCriterion("family_phone not between", value1, value2, "familyPhone");
            return (Criteria) this;
        }

        public Criteria andIntentionAreaIsNull() {
            addCriterion("intention_area is null");
            return (Criteria) this;
        }

        public Criteria andIntentionAreaIsNotNull() {
            addCriterion("intention_area is not null");
            return (Criteria) this;
        }

        public Criteria andIntentionAreaEqualTo(String value) {
            addCriterion("intention_area =", value, "intentionArea");
            return (Criteria) this;
        }

        public Criteria andIntentionAreaNotEqualTo(String value) {
            addCriterion("intention_area <>", value, "intentionArea");
            return (Criteria) this;
        }

        public Criteria andIntentionAreaGreaterThan(String value) {
            addCriterion("intention_area >", value, "intentionArea");
            return (Criteria) this;
        }

        public Criteria andIntentionAreaGreaterThanOrEqualTo(String value) {
            addCriterion("intention_area >=", value, "intentionArea");
            return (Criteria) this;
        }

        public Criteria andIntentionAreaLessThan(String value) {
            addCriterion("intention_area <", value, "intentionArea");
            return (Criteria) this;
        }

        public Criteria andIntentionAreaLessThanOrEqualTo(String value) {
            addCriterion("intention_area <=", value, "intentionArea");
            return (Criteria) this;
        }

        public Criteria andIntentionAreaLike(String value) {
            addCriterion("intention_area like", value, "intentionArea");
            return (Criteria) this;
        }

        public Criteria andIntentionAreaNotLike(String value) {
            addCriterion("intention_area not like", value, "intentionArea");
            return (Criteria) this;
        }

        public Criteria andIntentionAreaIn(List<String> values) {
            addCriterion("intention_area in", values, "intentionArea");
            return (Criteria) this;
        }

        public Criteria andIntentionAreaNotIn(List<String> values) {
            addCriterion("intention_area not in", values, "intentionArea");
            return (Criteria) this;
        }

        public Criteria andIntentionAreaBetween(String value1, String value2) {
            addCriterion("intention_area between", value1, value2, "intentionArea");
            return (Criteria) this;
        }

        public Criteria andIntentionAreaNotBetween(String value1, String value2) {
            addCriterion("intention_area not between", value1, value2, "intentionArea");
            return (Criteria) this;
        }

        public Criteria andOther3IsNull() {
            addCriterion("other3 is null");
            return (Criteria) this;
        }

        public Criteria andOther3IsNotNull() {
            addCriterion("other3 is not null");
            return (Criteria) this;
        }

        public Criteria andOther3EqualTo(String value) {
            addCriterion("other3 =", value, "other3");
            return (Criteria) this;
        }

        public Criteria andOther3NotEqualTo(String value) {
            addCriterion("other3 <>", value, "other3");
            return (Criteria) this;
        }

        public Criteria andOther3GreaterThan(String value) {
            addCriterion("other3 >", value, "other3");
            return (Criteria) this;
        }

        public Criteria andOther3GreaterThanOrEqualTo(String value) {
            addCriterion("other3 >=", value, "other3");
            return (Criteria) this;
        }

        public Criteria andOther3LessThan(String value) {
            addCriterion("other3 <", value, "other3");
            return (Criteria) this;
        }

        public Criteria andOther3LessThanOrEqualTo(String value) {
            addCriterion("other3 <=", value, "other3");
            return (Criteria) this;
        }

        public Criteria andOther3Like(String value) {
            addCriterion("other3 like", value, "other3");
            return (Criteria) this;
        }

        public Criteria andOther3NotLike(String value) {
            addCriterion("other3 not like", value, "other3");
            return (Criteria) this;
        }

        public Criteria andOther3In(List<String> values) {
            addCriterion("other3 in", values, "other3");
            return (Criteria) this;
        }

        public Criteria andOther3NotIn(List<String> values) {
            addCriterion("other3 not in", values, "other3");
            return (Criteria) this;
        }

        public Criteria andOther3Between(String value1, String value2) {
            addCriterion("other3 between", value1, value2, "other3");
            return (Criteria) this;
        }

        public Criteria andOther3NotBetween(String value1, String value2) {
            addCriterion("other3 not between", value1, value2, "other3");
            return (Criteria) this;
        }

        public Criteria andOther4IsNull() {
            addCriterion("other4 is null");
            return (Criteria) this;
        }

        public Criteria andOther4IsNotNull() {
            addCriterion("other4 is not null");
            return (Criteria) this;
        }

        public Criteria andOther4EqualTo(String value) {
            addCriterion("other4 =", value, "other4");
            return (Criteria) this;
        }

        public Criteria andOther4NotEqualTo(String value) {
            addCriterion("other4 <>", value, "other4");
            return (Criteria) this;
        }

        public Criteria andOther4GreaterThan(String value) {
            addCriterion("other4 >", value, "other4");
            return (Criteria) this;
        }

        public Criteria andOther4GreaterThanOrEqualTo(String value) {
            addCriterion("other4 >=", value, "other4");
            return (Criteria) this;
        }

        public Criteria andOther4LessThan(String value) {
            addCriterion("other4 <", value, "other4");
            return (Criteria) this;
        }

        public Criteria andOther4LessThanOrEqualTo(String value) {
            addCriterion("other4 <=", value, "other4");
            return (Criteria) this;
        }

        public Criteria andOther4Like(String value) {
            addCriterion("other4 like", value, "other4");
            return (Criteria) this;
        }

        public Criteria andOther4NotLike(String value) {
            addCriterion("other4 not like", value, "other4");
            return (Criteria) this;
        }

        public Criteria andOther4In(List<String> values) {
            addCriterion("other4 in", values, "other4");
            return (Criteria) this;
        }

        public Criteria andOther4NotIn(List<String> values) {
            addCriterion("other4 not in", values, "other4");
            return (Criteria) this;
        }

        public Criteria andOther4Between(String value1, String value2) {
            addCriterion("other4 between", value1, value2, "other4");
            return (Criteria) this;
        }

        public Criteria andOther4NotBetween(String value1, String value2) {
            addCriterion("other4 not between", value1, value2, "other4");
            return (Criteria) this;
        }

        public Criteria andIntentionalUnitNatureIsNull() {
            addCriterion("intentional_unit_nature is null");
            return (Criteria) this;
        }

        public Criteria andIntentionalUnitNatureIsNotNull() {
            addCriterion("intentional_unit_nature is not null");
            return (Criteria) this;
        }

        public Criteria andIntentionalUnitNatureEqualTo(String value) {
            addCriterion("intentional_unit_nature =", value, "intentionalUnitNature");
            return (Criteria) this;
        }

        public Criteria andIntentionalUnitNatureNotEqualTo(String value) {
            addCriterion("intentional_unit_nature <>", value, "intentionalUnitNature");
            return (Criteria) this;
        }

        public Criteria andIntentionalUnitNatureGreaterThan(String value) {
            addCriterion("intentional_unit_nature >", value, "intentionalUnitNature");
            return (Criteria) this;
        }

        public Criteria andIntentionalUnitNatureGreaterThanOrEqualTo(String value) {
            addCriterion("intentional_unit_nature >=", value, "intentionalUnitNature");
            return (Criteria) this;
        }

        public Criteria andIntentionalUnitNatureLessThan(String value) {
            addCriterion("intentional_unit_nature <", value, "intentionalUnitNature");
            return (Criteria) this;
        }

        public Criteria andIntentionalUnitNatureLessThanOrEqualTo(String value) {
            addCriterion("intentional_unit_nature <=", value, "intentionalUnitNature");
            return (Criteria) this;
        }

        public Criteria andIntentionalUnitNatureLike(String value) {
            addCriterion("intentional_unit_nature like", value, "intentionalUnitNature");
            return (Criteria) this;
        }

        public Criteria andIntentionalUnitNatureNotLike(String value) {
            addCriterion("intentional_unit_nature not like", value, "intentionalUnitNature");
            return (Criteria) this;
        }

        public Criteria andIntentionalUnitNatureIn(List<String> values) {
            addCriterion("intentional_unit_nature in", values, "intentionalUnitNature");
            return (Criteria) this;
        }

        public Criteria andIntentionalUnitNatureNotIn(List<String> values) {
            addCriterion("intentional_unit_nature not in", values, "intentionalUnitNature");
            return (Criteria) this;
        }

        public Criteria andIntentionalUnitNatureBetween(String value1, String value2) {
            addCriterion("intentional_unit_nature between", value1, value2, "intentionalUnitNature");
            return (Criteria) this;
        }

        public Criteria andIntentionalUnitNatureNotBetween(String value1, String value2) {
            addCriterion("intentional_unit_nature not between", value1, value2, "intentionalUnitNature");
            return (Criteria) this;
        }

        public Criteria andIntentionalUnitIndustryIsNull() {
            addCriterion("intentional_unit_industry is null");
            return (Criteria) this;
        }

        public Criteria andIntentionalUnitIndustryIsNotNull() {
            addCriterion("intentional_unit_industry is not null");
            return (Criteria) this;
        }

        public Criteria andIntentionalUnitIndustryEqualTo(String value) {
            addCriterion("intentional_unit_industry =", value, "intentionalUnitIndustry");
            return (Criteria) this;
        }

        public Criteria andIntentionalUnitIndustryNotEqualTo(String value) {
            addCriterion("intentional_unit_industry <>", value, "intentionalUnitIndustry");
            return (Criteria) this;
        }

        public Criteria andIntentionalUnitIndustryGreaterThan(String value) {
            addCriterion("intentional_unit_industry >", value, "intentionalUnitIndustry");
            return (Criteria) this;
        }

        public Criteria andIntentionalUnitIndustryGreaterThanOrEqualTo(String value) {
            addCriterion("intentional_unit_industry >=", value, "intentionalUnitIndustry");
            return (Criteria) this;
        }

        public Criteria andIntentionalUnitIndustryLessThan(String value) {
            addCriterion("intentional_unit_industry <", value, "intentionalUnitIndustry");
            return (Criteria) this;
        }

        public Criteria andIntentionalUnitIndustryLessThanOrEqualTo(String value) {
            addCriterion("intentional_unit_industry <=", value, "intentionalUnitIndustry");
            return (Criteria) this;
        }

        public Criteria andIntentionalUnitIndustryLike(String value) {
            addCriterion("intentional_unit_industry like", value, "intentionalUnitIndustry");
            return (Criteria) this;
        }

        public Criteria andIntentionalUnitIndustryNotLike(String value) {
            addCriterion("intentional_unit_industry not like", value, "intentionalUnitIndustry");
            return (Criteria) this;
        }

        public Criteria andIntentionalUnitIndustryIn(List<String> values) {
            addCriterion("intentional_unit_industry in", values, "intentionalUnitIndustry");
            return (Criteria) this;
        }

        public Criteria andIntentionalUnitIndustryNotIn(List<String> values) {
            addCriterion("intentional_unit_industry not in", values, "intentionalUnitIndustry");
            return (Criteria) this;
        }

        public Criteria andIntentionalUnitIndustryBetween(String value1, String value2) {
            addCriterion("intentional_unit_industry between", value1, value2, "intentionalUnitIndustry");
            return (Criteria) this;
        }

        public Criteria andIntentionalUnitIndustryNotBetween(String value1, String value2) {
            addCriterion("intentional_unit_industry not between", value1, value2, "intentionalUnitIndustry");
            return (Criteria) this;
        }

        public Criteria andIntentionalJobCategoryIsNull() {
            addCriterion("intentional_job_category is null");
            return (Criteria) this;
        }

        public Criteria andIntentionalJobCategoryIsNotNull() {
            addCriterion("intentional_job_category is not null");
            return (Criteria) this;
        }

        public Criteria andIntentionalJobCategoryEqualTo(String value) {
            addCriterion("intentional_job_category =", value, "intentionalJobCategory");
            return (Criteria) this;
        }

        public Criteria andIntentionalJobCategoryNotEqualTo(String value) {
            addCriterion("intentional_job_category <>", value, "intentionalJobCategory");
            return (Criteria) this;
        }

        public Criteria andIntentionalJobCategoryGreaterThan(String value) {
            addCriterion("intentional_job_category >", value, "intentionalJobCategory");
            return (Criteria) this;
        }

        public Criteria andIntentionalJobCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("intentional_job_category >=", value, "intentionalJobCategory");
            return (Criteria) this;
        }

        public Criteria andIntentionalJobCategoryLessThan(String value) {
            addCriterion("intentional_job_category <", value, "intentionalJobCategory");
            return (Criteria) this;
        }

        public Criteria andIntentionalJobCategoryLessThanOrEqualTo(String value) {
            addCriterion("intentional_job_category <=", value, "intentionalJobCategory");
            return (Criteria) this;
        }

        public Criteria andIntentionalJobCategoryLike(String value) {
            addCriterion("intentional_job_category like", value, "intentionalJobCategory");
            return (Criteria) this;
        }

        public Criteria andIntentionalJobCategoryNotLike(String value) {
            addCriterion("intentional_job_category not like", value, "intentionalJobCategory");
            return (Criteria) this;
        }

        public Criteria andIntentionalJobCategoryIn(List<String> values) {
            addCriterion("intentional_job_category in", values, "intentionalJobCategory");
            return (Criteria) this;
        }

        public Criteria andIntentionalJobCategoryNotIn(List<String> values) {
            addCriterion("intentional_job_category not in", values, "intentionalJobCategory");
            return (Criteria) this;
        }

        public Criteria andIntentionalJobCategoryBetween(String value1, String value2) {
            addCriterion("intentional_job_category between", value1, value2, "intentionalJobCategory");
            return (Criteria) this;
        }

        public Criteria andIntentionalJobCategoryNotBetween(String value1, String value2) {
            addCriterion("intentional_job_category not between", value1, value2, "intentionalJobCategory");
            return (Criteria) this;
        }

        public Criteria andIntentionalMonthlySalaryIsNull() {
            addCriterion("intentional_monthly_salary is null");
            return (Criteria) this;
        }

        public Criteria andIntentionalMonthlySalaryIsNotNull() {
            addCriterion("intentional_monthly_salary is not null");
            return (Criteria) this;
        }

        public Criteria andIntentionalMonthlySalaryEqualTo(String value) {
            addCriterion("intentional_monthly_salary =", value, "intentionalMonthlySalary");
            return (Criteria) this;
        }

        public Criteria andIntentionalMonthlySalaryNotEqualTo(String value) {
            addCriterion("intentional_monthly_salary <>", value, "intentionalMonthlySalary");
            return (Criteria) this;
        }

        public Criteria andIntentionalMonthlySalaryGreaterThan(String value) {
            addCriterion("intentional_monthly_salary >", value, "intentionalMonthlySalary");
            return (Criteria) this;
        }

        public Criteria andIntentionalMonthlySalaryGreaterThanOrEqualTo(String value) {
            addCriterion("intentional_monthly_salary >=", value, "intentionalMonthlySalary");
            return (Criteria) this;
        }

        public Criteria andIntentionalMonthlySalaryLessThan(String value) {
            addCriterion("intentional_monthly_salary <", value, "intentionalMonthlySalary");
            return (Criteria) this;
        }

        public Criteria andIntentionalMonthlySalaryLessThanOrEqualTo(String value) {
            addCriterion("intentional_monthly_salary <=", value, "intentionalMonthlySalary");
            return (Criteria) this;
        }

        public Criteria andIntentionalMonthlySalaryLike(String value) {
            addCriterion("intentional_monthly_salary like", value, "intentionalMonthlySalary");
            return (Criteria) this;
        }

        public Criteria andIntentionalMonthlySalaryNotLike(String value) {
            addCriterion("intentional_monthly_salary not like", value, "intentionalMonthlySalary");
            return (Criteria) this;
        }

        public Criteria andIntentionalMonthlySalaryIn(List<String> values) {
            addCriterion("intentional_monthly_salary in", values, "intentionalMonthlySalary");
            return (Criteria) this;
        }

        public Criteria andIntentionalMonthlySalaryNotIn(List<String> values) {
            addCriterion("intentional_monthly_salary not in", values, "intentionalMonthlySalary");
            return (Criteria) this;
        }

        public Criteria andIntentionalMonthlySalaryBetween(String value1, String value2) {
            addCriterion("intentional_monthly_salary between", value1, value2, "intentionalMonthlySalary");
            return (Criteria) this;
        }

        public Criteria andIntentionalMonthlySalaryNotBetween(String value1, String value2) {
            addCriterion("intentional_monthly_salary not between", value1, value2, "intentionalMonthlySalary");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table source_of_student
     *
     * @mbg.generated do_not_delete_during_merge Tue May 14 16:52:26 JST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table source_of_student
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}