package cn.com.meguru.entity;

public class StatusOfStudent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status_of_student.id
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status_of_student.college
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String college;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status_of_student.faculty
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String faculty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status_of_student.student_id
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status_of_student.name
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status_of_student.ID_Card
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status_of_student.gender
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status_of_student.education
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String education;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status_of_student.profession
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String profession;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status_of_student.faculty_code
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String facultyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status_of_student.profession_code
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String professionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status_of_student.student_code
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String studentCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status_of_student.id
     *
     * @return the value of status_of_student.id
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status_of_student.id
     *
     * @param id the value for status_of_student.id
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status_of_student.college
     *
     * @return the value of status_of_student.college
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getCollege() {
        return college;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status_of_student.college
     *
     * @param college the value for status_of_student.college
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setCollege(String college) {
        this.college = college == null ? null : college.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status_of_student.faculty
     *
     * @return the value of status_of_student.faculty
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getFaculty() {
        return faculty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status_of_student.faculty
     *
     * @param faculty the value for status_of_student.faculty
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setFaculty(String faculty) {
        this.faculty = faculty == null ? null : faculty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status_of_student.student_id
     *
     * @return the value of status_of_student.student_id
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status_of_student.student_id
     *
     * @param studentId the value for status_of_student.student_id
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status_of_student.name
     *
     * @return the value of status_of_student.name
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status_of_student.name
     *
     * @param name the value for status_of_student.name
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status_of_student.ID_Card
     *
     * @return the value of status_of_student.ID_Card
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status_of_student.ID_Card
     *
     * @param idCard the value for status_of_student.ID_Card
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status_of_student.gender
     *
     * @return the value of status_of_student.gender
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status_of_student.gender
     *
     * @param gender the value for status_of_student.gender
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status_of_student.education
     *
     * @return the value of status_of_student.education
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status_of_student.education
     *
     * @param education the value for status_of_student.education
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status_of_student.profession
     *
     * @return the value of status_of_student.profession
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getProfession() {
        return profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status_of_student.profession
     *
     * @param profession the value for status_of_student.profession
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setProfession(String profession) {
        this.profession = profession == null ? null : profession.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status_of_student.faculty_code
     *
     * @return the value of status_of_student.faculty_code
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getFacultyCode() {
        return facultyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status_of_student.faculty_code
     *
     * @param facultyCode the value for status_of_student.faculty_code
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setFacultyCode(String facultyCode) {
        this.facultyCode = facultyCode == null ? null : facultyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status_of_student.profession_code
     *
     * @return the value of status_of_student.profession_code
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getProfessionCode() {
        return professionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status_of_student.profession_code
     *
     * @param professionCode the value for status_of_student.profession_code
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setProfessionCode(String professionCode) {
        this.professionCode = professionCode == null ? null : professionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status_of_student.student_code
     *
     * @return the value of status_of_student.student_code
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getStudentCode() {
        return studentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status_of_student.student_code
     *
     * @param studentCode the value for status_of_student.student_code
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setStudentCode(String studentCode) {
        this.studentCode = studentCode == null ? null : studentCode.trim();
    }
}