package cn.com.meguru.entity;

import java.util.Date;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.college
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String college;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.faculty
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String faculty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_id
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.name
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.ID_Card
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.gender
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.education
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String education;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.profession
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String profession;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.educational_system
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private Byte educationalSystem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.degree
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String degree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.training_method
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String trainingMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.graduation_year
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String graduationYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.professional_direction
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String professionalDirection;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.marital_status
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String maritalStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.political_status
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String politicalStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.nationality
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String nationality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.date_of_birth
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private Date dateOfBirth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.date_of_start_school
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private Date dateOfStartSchool;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.majoring_in_foreign_language
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String majoringInForeignLanguage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.city_or_village
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String cityOrVillage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.account_to_school
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String accountToSchool;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.archives_to_school
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String archivesToSchool;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.majoring_in_foreign_language_level
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String majoringInForeignLanguageLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.home_address
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String homeAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_area
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String studentArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.other1
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String other1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.other2
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String other2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.home_zip_code
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String homeZipCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.is_teacher_training
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String isTeacherTraining;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.qq
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.family_contact
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String familyContact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.family_phone
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String familyPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.intention_area
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String intentionArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.other3
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String other3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.other4
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String other4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.intentional_unit_nature
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String intentionalUnitNature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.intentional_unit_industry
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String intentionalUnitIndustry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.intentional_job_category
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String intentionalJobCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.intentional_monthly_salary
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String intentionalMonthlySalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.email
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.phone
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id
     *
     * @return the value of student.id
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id
     *
     * @param id the value for student.id
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.college
     *
     * @return the value of student.college
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getCollege() {
        return college;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.college
     *
     * @param college the value for student.college
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setCollege(String college) {
        this.college = college == null ? null : college.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.faculty
     *
     * @return the value of student.faculty
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getFaculty() {
        return faculty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.faculty
     *
     * @param faculty the value for student.faculty
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setFaculty(String faculty) {
        this.faculty = faculty == null ? null : faculty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_id
     *
     * @return the value of student.student_id
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_id
     *
     * @param studentId the value for student.student_id
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.name
     *
     * @return the value of student.name
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.name
     *
     * @param name the value for student.name
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.ID_Card
     *
     * @return the value of student.ID_Card
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.ID_Card
     *
     * @param idCard the value for student.ID_Card
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.gender
     *
     * @return the value of student.gender
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.gender
     *
     * @param gender the value for student.gender
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.education
     *
     * @return the value of student.education
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.education
     *
     * @param education the value for student.education
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.profession
     *
     * @return the value of student.profession
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getProfession() {
        return profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.profession
     *
     * @param profession the value for student.profession
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setProfession(String profession) {
        this.profession = profession == null ? null : profession.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.educational_system
     *
     * @return the value of student.educational_system
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public Byte getEducationalSystem() {
        return educationalSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.educational_system
     *
     * @param educationalSystem the value for student.educational_system
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setEducationalSystem(Byte educationalSystem) {
        this.educationalSystem = educationalSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.degree
     *
     * @return the value of student.degree
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.degree
     *
     * @param degree the value for student.degree
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setDegree(String degree) {
        this.degree = degree == null ? null : degree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.training_method
     *
     * @return the value of student.training_method
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getTrainingMethod() {
        return trainingMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.training_method
     *
     * @param trainingMethod the value for student.training_method
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setTrainingMethod(String trainingMethod) {
        this.trainingMethod = trainingMethod == null ? null : trainingMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.graduation_year
     *
     * @return the value of student.graduation_year
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getGraduationYear() {
        return graduationYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.graduation_year
     *
     * @param graduationYear the value for student.graduation_year
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setGraduationYear(String graduationYear) {
        this.graduationYear = graduationYear == null ? null : graduationYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.professional_direction
     *
     * @return the value of student.professional_direction
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getProfessionalDirection() {
        return professionalDirection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.professional_direction
     *
     * @param professionalDirection the value for student.professional_direction
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setProfessionalDirection(String professionalDirection) {
        this.professionalDirection = professionalDirection == null ? null : professionalDirection.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.marital_status
     *
     * @return the value of student.marital_status
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getMaritalStatus() {
        return maritalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.marital_status
     *
     * @param maritalStatus the value for student.marital_status
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setMaritalStatus(String maritalStatus) {
        this.maritalStatus = maritalStatus == null ? null : maritalStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.political_status
     *
     * @return the value of student.political_status
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getPoliticalStatus() {
        return politicalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.political_status
     *
     * @param politicalStatus the value for student.political_status
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setPoliticalStatus(String politicalStatus) {
        this.politicalStatus = politicalStatus == null ? null : politicalStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.nationality
     *
     * @return the value of student.nationality
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.nationality
     *
     * @param nationality the value for student.nationality
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setNationality(String nationality) {
        this.nationality = nationality == null ? null : nationality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.date_of_birth
     *
     * @return the value of student.date_of_birth
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public Date getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.date_of_birth
     *
     * @param dateOfBirth the value for student.date_of_birth
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.date_of_start_school
     *
     * @return the value of student.date_of_start_school
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public Date getDateOfStartSchool() {
        return dateOfStartSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.date_of_start_school
     *
     * @param dateOfStartSchool the value for student.date_of_start_school
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setDateOfStartSchool(Date dateOfStartSchool) {
        this.dateOfStartSchool = dateOfStartSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.majoring_in_foreign_language
     *
     * @return the value of student.majoring_in_foreign_language
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getMajoringInForeignLanguage() {
        return majoringInForeignLanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.majoring_in_foreign_language
     *
     * @param majoringInForeignLanguage the value for student.majoring_in_foreign_language
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setMajoringInForeignLanguage(String majoringInForeignLanguage) {
        this.majoringInForeignLanguage = majoringInForeignLanguage == null ? null : majoringInForeignLanguage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.city_or_village
     *
     * @return the value of student.city_or_village
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getCityOrVillage() {
        return cityOrVillage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.city_or_village
     *
     * @param cityOrVillage the value for student.city_or_village
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setCityOrVillage(String cityOrVillage) {
        this.cityOrVillage = cityOrVillage == null ? null : cityOrVillage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.account_to_school
     *
     * @return the value of student.account_to_school
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getAccountToSchool() {
        return accountToSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.account_to_school
     *
     * @param accountToSchool the value for student.account_to_school
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setAccountToSchool(String accountToSchool) {
        this.accountToSchool = accountToSchool == null ? null : accountToSchool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.archives_to_school
     *
     * @return the value of student.archives_to_school
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getArchivesToSchool() {
        return archivesToSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.archives_to_school
     *
     * @param archivesToSchool the value for student.archives_to_school
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setArchivesToSchool(String archivesToSchool) {
        this.archivesToSchool = archivesToSchool == null ? null : archivesToSchool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.majoring_in_foreign_language_level
     *
     * @return the value of student.majoring_in_foreign_language_level
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getMajoringInForeignLanguageLevel() {
        return majoringInForeignLanguageLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.majoring_in_foreign_language_level
     *
     * @param majoringInForeignLanguageLevel the value for student.majoring_in_foreign_language_level
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setMajoringInForeignLanguageLevel(String majoringInForeignLanguageLevel) {
        this.majoringInForeignLanguageLevel = majoringInForeignLanguageLevel == null ? null : majoringInForeignLanguageLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.home_address
     *
     * @return the value of student.home_address
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getHomeAddress() {
        return homeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.home_address
     *
     * @param homeAddress the value for student.home_address
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setHomeAddress(String homeAddress) {
        this.homeAddress = homeAddress == null ? null : homeAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_area
     *
     * @return the value of student.student_area
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getStudentArea() {
        return studentArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_area
     *
     * @param studentArea the value for student.student_area
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setStudentArea(String studentArea) {
        this.studentArea = studentArea == null ? null : studentArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.other1
     *
     * @return the value of student.other1
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getOther1() {
        return other1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.other1
     *
     * @param other1 the value for student.other1
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setOther1(String other1) {
        this.other1 = other1 == null ? null : other1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.other2
     *
     * @return the value of student.other2
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getOther2() {
        return other2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.other2
     *
     * @param other2 the value for student.other2
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setOther2(String other2) {
        this.other2 = other2 == null ? null : other2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.home_zip_code
     *
     * @return the value of student.home_zip_code
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getHomeZipCode() {
        return homeZipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.home_zip_code
     *
     * @param homeZipCode the value for student.home_zip_code
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setHomeZipCode(String homeZipCode) {
        this.homeZipCode = homeZipCode == null ? null : homeZipCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.is_teacher_training
     *
     * @return the value of student.is_teacher_training
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getIsTeacherTraining() {
        return isTeacherTraining;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.is_teacher_training
     *
     * @param isTeacherTraining the value for student.is_teacher_training
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setIsTeacherTraining(String isTeacherTraining) {
        this.isTeacherTraining = isTeacherTraining == null ? null : isTeacherTraining.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.qq
     *
     * @return the value of student.qq
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.qq
     *
     * @param qq the value for student.qq
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.family_contact
     *
     * @return the value of student.family_contact
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getFamilyContact() {
        return familyContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.family_contact
     *
     * @param familyContact the value for student.family_contact
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setFamilyContact(String familyContact) {
        this.familyContact = familyContact == null ? null : familyContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.family_phone
     *
     * @return the value of student.family_phone
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getFamilyPhone() {
        return familyPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.family_phone
     *
     * @param familyPhone the value for student.family_phone
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setFamilyPhone(String familyPhone) {
        this.familyPhone = familyPhone == null ? null : familyPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.intention_area
     *
     * @return the value of student.intention_area
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getIntentionArea() {
        return intentionArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.intention_area
     *
     * @param intentionArea the value for student.intention_area
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setIntentionArea(String intentionArea) {
        this.intentionArea = intentionArea == null ? null : intentionArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.other3
     *
     * @return the value of student.other3
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getOther3() {
        return other3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.other3
     *
     * @param other3 the value for student.other3
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setOther3(String other3) {
        this.other3 = other3 == null ? null : other3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.other4
     *
     * @return the value of student.other4
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getOther4() {
        return other4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.other4
     *
     * @param other4 the value for student.other4
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setOther4(String other4) {
        this.other4 = other4 == null ? null : other4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.intentional_unit_nature
     *
     * @return the value of student.intentional_unit_nature
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getIntentionalUnitNature() {
        return intentionalUnitNature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.intentional_unit_nature
     *
     * @param intentionalUnitNature the value for student.intentional_unit_nature
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setIntentionalUnitNature(String intentionalUnitNature) {
        this.intentionalUnitNature = intentionalUnitNature == null ? null : intentionalUnitNature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.intentional_unit_industry
     *
     * @return the value of student.intentional_unit_industry
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getIntentionalUnitIndustry() {
        return intentionalUnitIndustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.intentional_unit_industry
     *
     * @param intentionalUnitIndustry the value for student.intentional_unit_industry
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setIntentionalUnitIndustry(String intentionalUnitIndustry) {
        this.intentionalUnitIndustry = intentionalUnitIndustry == null ? null : intentionalUnitIndustry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.intentional_job_category
     *
     * @return the value of student.intentional_job_category
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getIntentionalJobCategory() {
        return intentionalJobCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.intentional_job_category
     *
     * @param intentionalJobCategory the value for student.intentional_job_category
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setIntentionalJobCategory(String intentionalJobCategory) {
        this.intentionalJobCategory = intentionalJobCategory == null ? null : intentionalJobCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.intentional_monthly_salary
     *
     * @return the value of student.intentional_monthly_salary
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getIntentionalMonthlySalary() {
        return intentionalMonthlySalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.intentional_monthly_salary
     *
     * @param intentionalMonthlySalary the value for student.intentional_monthly_salary
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setIntentionalMonthlySalary(String intentionalMonthlySalary) {
        this.intentionalMonthlySalary = intentionalMonthlySalary == null ? null : intentionalMonthlySalary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.email
     *
     * @return the value of student.email
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.email
     *
     * @param email the value for student.email
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.phone
     *
     * @return the value of student.phone
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.phone
     *
     * @param phone the value for student.phone
     *
     * @mbg.generated Tue May 14 16:52:26 JST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }
}